# Generated by Django 4.0 on 2024-03-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0002_alter_comment_author_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table="'core.comment'",
        ),
    ]
