# Generated by Django 4.0 on 2024-03-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0003_alter_comment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
