# Generated by Django 4.0 on 2024-03-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_user_posts_liked'),
        ('core_post', '0005_alter_post_table'),
        ('core_comment', '0004_alter_comment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_user.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_post.post'),
        ),
    ]
