# Generated by Django 4.0 on 2024-03-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0003_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
